# Model arguments
model_name_or_path: mehuldamani/qwen-base-verifier-sft-v1
run_name: "SFT-RLCR-math"
output_dir: data/SFT-RLCR-math
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: mehuldamani/big-math-digits
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# GRPO trainer config
bf16: true
beta: 0.0
eval_strategy: "steps"
eval_steps: 50
eval_on_start: false 
format_pattern: "tabc"
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_strategy: "end"
learning_rate: 5e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: linear
mask_truncated_completions: true
max_prompt_length: 1024
max_completion_length: 4096
max_steps: -1
num_generations: 32
num_iterations: 1
num_train_epochs: 0.5
overwrite_output_dir: true
per_device_eval_batch_size: 32
per_device_train_batch_size: 6
push_to_hub: true
report_to:
- wandb
reward_funcs: ["format","accuracy","brier","mean_confidence","confidence_one_or_zero"]
reward_weights: [0.5,0.5,0.5,0.00001,0.00001]
save_strategy: "steps"
save_steps: 60
save_total_limit: 1
scale_rewards : false 
seed: 43
sys_prompt_name: "tabc"
temperature: 0.7
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.4
warmup_ratio: 0.20
