# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B
run_name: "RLVR-hotpot"
output_dir: data/RLVR-hotpot
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: mehuldamani/hotpot_qa
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# GRPO trainer config
bf16: true
beta: 0.0
eval_strategy: "steps"
eval_steps: 50
eval_on_start: false 
format_pattern: "ta"
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_strategy: "end"
learning_rate: 1e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
max_prompt_length: 3072
max_completion_length: 1536
max_steps: -1
num_generations: 32
num_iterations: 1
num_train_epochs: 1
overwrite_output_dir: true
per_device_eval_batch_size: 32
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- wandb
reward_funcs: ["format","accuracy","brier","mean_confidence","confidence_one_or_zero"]
reward_weights: [0.5,0.5,0.000001,0.000001,0.000001]
save_strategy: "steps"
save_steps: 60
save_total_limit: 1
scale_rewards: false
seed: 43
sys_prompt_name: "gen"
temperature: 0.7
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.4
warmup_ratio: 0.05
